language: node_js
node_js:
- '6'
- '8'
services:
- rabbitmq
deploy:
  provider: npm
  email: integration-dev@thomascookonline.com
  api_key:
    secure: GCaVn+/Qj/KlXTHMSZv3q8S6jH1OgyTJEQoJzxCSFZv9koHkqZ024YsFoRej8nawuT/RB9+Y5QSqDE8600Se7B9LNZxMgAPidHqTJHbcamlrZw1itTkqQ1bq5msfYEHC36hmHVoa6jj+dGLgABEh06KfG5qhhssGkFQWRe9fwKOeAHZI0Tygz1hE3N2/ROWUbVbuuGFayoFJX5xW3mm9JF6wpbGaYAKkhF9Y3DsxbLa9FcsIoLyciLcBBVtPZyeuIDW9Yy4tyk3x6arxKFVTevDGnlxCPIObriL5o2vZHzT5tlD8uqjxVUMNS4OOfCoJwnKKDjArLd2g/LmTlO0JIjBMUHJuZPqmlwFVgfVma74Oh97X94TQ3gW/vU9/aPy3iOZ8opP4cjmYeih8YCUWQ7gcs0V887pYKM8j/HBDuDhr/cY6E0XJ6VzCv2mdD9ZzRlwH2Y15m74gPCAXYzGDqdTt0TdPucn5MxEs9bWMTkWv1y0Wg1XVSC2mTtoAoPAwI43tuTjR2BkQ4oppAxOs6o4NthLU+tnJQkjDmop6AQO3xjOMXaW4t3w9aV47mfrDtCdXWFk0/MYHzRdCOvuCxi3tGmcOE90eOep0NoHbTsP2WJlfXHcOyAH3MFMOLgeVFrMXDPUFlyhXpTX/nSanyLuY9Z1H5rQ200Vb56g9HRk=
  on:
    tags: true
    repo: tcdl/newrelic-amqp-coffee
    node: '8'
